### PR TITLE
Multi key selection

### PR DESCRIPTION
**Pull request by ethanmsmith**
Added buttons and functionality for selecting multiple keys lighting at once.
(e.g. WASD, Num Row, IJKL, etc.)

### CODE REVIEW

**Comment by kprinssu** [comment]
Please let me know when you have finished your changes. I'll do verify and merge in the changes.

**Comment by ethanmsmith** [comment]
So all my changes for multi key selection are done. I changed the buttons to be coloured in the selected colour and not just outlined. Added a button to copy a colour from an already assigned key.

A known bug is the `selectedColour` when copying gets updated, but it is not reflected in the colourpicker.

**Comment by kprinssu** [comment]
I believe that you have to explicitly set the colour picker. If you are done with the changes, I'll merge them in.

**Comment by ethanmsmith** [comment]
Yeah, changes are done.

**Pull request merged**
